### ISSUE TITLE
Install codecov on CI

### ISSUE THREAD

**Issue by l-vo** [Coffreo/ceph-odm#43]
Require to add application codecov to organization (Coffreo). @coupelon should have the permissions to do that.
Steps:
* [ ] Search `codecov` in github Marketplace. At the bottom of the codecov application page, chose open source (free) and the account Coffreo (you must have the permissions on Coffreo for doing that). Click on "install it for free".
* [ ] In the project (ceph-odm) settings, go to `Branches` and edit the master branch protection rules. In the "*Require status checks to pass before merging*" section, you should see continuous-integration/travis-ci checked and codecov/patch, codecov/project unchecked. Check it according to the screenshot below.

<img width="738" alt="capture d ecran 2019-02-12 a 10 45 19" src="https://user-images.githubusercontent.com/15314293/52626386-5618cb80-2eb3-11e9-827d-18d9d4003814.png">

**Comment by emri99** [comment]
@l-vo: I'm unable to get `codecov/path` and `codecov/project` displayed like above screenshots even after following installation steps. 

Codecov.io didn't convince me that much, from what I understand, it needs [sourcegraph extension](https://github.com/sourcegraph/sourcegraph-codecov#readme) to show coverage infos in PR. Maybe it can be done with team bots, but documentation link leads to 404 :(

I'm considering to move to another code coverage tool.

Did I miss something ?

**Comment by l-vo** [comment]
@emri99 has codecov application been added to Coffreo organizaton ? (first step of the issue) ? If Coffreo hasn't the application you can't see `codecov/path` and `codecov/project`.

I'm not sure I have already used **sourcegraph extension**. If you look [here](https://github.com/l-vo/photos-picker/pull/72), the detailed code coverage is visible from the codecov site but accessible from the PR. But the main goal of this tool here si not to show code coverage on PR, it is to decline PRs which the code reduces code coverage percentage. 

I don't know if some other tools are better or not, but this one is language-agnostic and does its job so... :)

**Comment by emri99** [comment]
Yes, codecov has been added yesterday.
I tried to applied it on all organizations repos, or only ceph-odm, both in vain.
There is still a warning in codecov project settings page, standing `GitHub Integration is installed. However, this repository is not enabled.`

**Comment by l-vo** [comment]
Indeed, it doesn't seem to be a permission problem. Maybe it's a bit more tricky than in my memories. I'm going to take a look at it, thank you for your clarifications :)

**Comment by l-vo** [comment]
@emri99 could you however check with a (the ?) Coffreo group administrator account that the repository is correctly activated ?
In this page:
<img width="1440" alt="Capture d’écran 2019-04-18 à 16 06 17" src="https://user-images.githubusercontent.com/15314293/56366919-76873e00-61f4-11e9-93cb-82edbc5ede5b.png">
You should have something like this when clicking on **configure**:
<img width="1440" alt="Capture d’écran 2019-04-18 à 16 07 47" src="https://user-images.githubusercontent.com/15314293/56366998-961e6680-61f4-11e9-9905-e4625a869b67.png">

**Comment by emri99** [comment]
That's what I've done yesterday (I'm now owner of organization).

I've just post on codecov forum.
https://community.codecov.io/t/github-integration-not-enabled/137

**Comment by l-vo** [comment]
@emri99 It was simpler than that, the last PR was too old for displaying codecov checks. Thanks for your help :)

**Comment by emri99** [comment]
Yeah ! It works ! :)

I force to redeliver webhooks after changing configurations, wait a little bit and it appears as expected.
I think process must be triggered on codecov for github to be noticed of available statuses

**Comment by l-vo** [comment]
See #59
